


drop table topic if exists;
create table topic
(
    id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255)
);

drop table discussion if exists;
create table discussion
(
    id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time timestamp,
    user_id int,
    topic_id int,
    comment varchar(2000)
);

drop table users if exists;
create table users
(
    id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    varchar(255),
    password    varchar(255),
    user_status int
);